let product = [
  {
    id: 1,
    name: "Bold Statement Finger Ring For Men",
    productDetails:
      "This bold and sophisticated finger ring for men featuring nine precious gemstones and diamonds is a standout accessory for any occasion. The stylish design is perfect for the modern man who appreciates a distinctive look for his daily wear.",
    price: 10000.0,
    quantity: 1,
    image: "/assets/images/Ring/Men/Ring1.webp",
    category: "Rings",
    gender: "Men",
    occasion: "Traditional And Ethnic Wear",
    karatage: 18,
    materialColor: "Yellow",
  },
  {
    id: 2,
    name: "Hexagonal Maze Finger Ring For Men",
    productDetails:
      "Express your uniquely individualistic style with this quirky hexagonal diamond center finger ring which makes a statement of its own and ensures you always stand out in a crowd. Set your own trends and bask in glory daily with this fashionable ring.",
    price: 8000.0,
    quantity: 1,
    image: "/assets/images/Ring/Men/Ring2.webp",
    category: "Rings",
    gender: "Men",
    occasion: "Modern Wear",
    karatage: 18,
    materialColor: "Yellow",
  },
  {
    id: 3,
    name: "Glamourous Dazzle Finger Ring For Men",
    productDetails:
      "An arresting design of diamonds with a tiny silver center sets this ring apart. A symbol of refined elegance, this ring effortlessly transitions from formal occasions to casual settings, adding a touch of sophistication to your everyday style.",
    price: 12000.0,
    quantity: 1,
    image: "/assets/images/Ring/Men/Ring3.webp",
    category: "Rings",
    gender: "Men",
    occasion: "Office Wear",
    karatage: 18,
    materialColor: "Yellow",
  },
  {
    id: 4,
    name: "Vogueish Charm Platinum Ring For Men",
    productDetails:
      "xuding vogueish charm and endearing allure, this platinum ring is meticulously crafted for the connoisseur with refined taste. Infusing an extra edge of sophistication, it transcends the fleeting trends.",
    price: 15000.0,
    quantity: 1,
    image: "/assets/images/Ring/Men/Ring4.webp",
    category: "Rings",
    gender: "Men",
    occasion: "Casual Wear",
    karatage: 95,
    materialColor: "Platinum",
  },
  {
    id: 5,
    name: "Dazzling Radiance Finger Ring For Men",
    productDetails:
      "A stunningly patterned rose gold band gently nestles the dazzling brilliance of diamonds in this one of a kind finger ring which exudes luxurious panache. Pair it effortlessly with any daily attire to make your mark with this symbol of confidence.",
    price: 18000.0,
    quantity: 1,
    image: "/assets/images/Ring/Men/Ring5.webp",
    category: "Rings",
    gender: "Men",
    occasion: "Modern Wear",
    karatage: 18,
    materialColor: "Rose Gold",
  },
  {
    id: 6,
    name: "Bold Star Power Ring",
    productDetails:
      "Don't shy away from making an edgy statement when you adorn this bold ring with black enamel and star motif!",
    price: 20000.0,
    quantity: 1,
    image: "/assets/images/Ring/Men/Ring6.webp",
    category: "Rings",
    gender: "Men",
    occasion: "Casual Wear",
    karatage: 22,
    materialColor: "Yellow",
  },
  {
    id: 7,
    name: "Sublime Enamelled Ring for Men",
    productDetails:
      "This sublime ring is simple yet impactful accessory for the man who wishes to make an unforgettable style statement wherever he goes!",
    price: 22000.0,
    quantity: 1,
    image: "/assets/images/Ring/Men/Ring7.webp",
    category: "Rings",
    gender: "Men",
    occasion: "Casual Wear",
    karatage: 22,
    materialColor: "Yellow",
  },
  {
    id: 8,
    name: "Dapper Charm Ring For Men",
    productDetails:
      "Bring in dapper charm to your look with this enchanting men's gold ring, a meaningful symbol of contemporary allure and timeless sophistication.",
    price: 25000.0,
    quantity: 1,
    image: "/assets/images/Ring/Men/Ring8.webp",
    category: "Rings",
    gender: "Men",
    occasion: "Casual Wear",
    karatage: 22,
    materialColor: "Yellow",
  },
  {
    id: 9,
    name: "Gleaming Flower Diamond Ring ",
    productDetails:
      "The lush beauty of this floral ring is designed to give your style a flourish of glamour. Indulge in the grace of nature and leave everyone bedazzled with this piece.",
    price: 10000.0,
    quantity: 1,
    image: "/assets/images/Ring/WomenRing/Ring1.webp",
    category: "Rings",
    gender: "Women",
    occasion: "Office Wear",
    karatage: 18,
  },
  {
    id: 10,
    name: "Shimmering Flower Diamond Ring",
    productDetails:
      "This ring carries a flower motif that's encrusted with shimmering diamonds. Its artistic allure is just what you need to elevate your daily style!",
    price: 8000.0,
    quantity: 1,
    image: "/assets/images/Ring/WomenRing/Ring2.webp",
    category: "Rings",
    gender: "Women",
    occasion: "Office Wear",
    karatage: 18,
  },
  {
    id: 11,
    name: "Eclectic Squares Diamond Ring",
    productDetails:
      "Unique, eclectic and oh, so charming! The square patterns and dazzling diamonds in this ring will never fail to make you stand out from the crowd!",
    price: 12000.0,
    quantity: 1,
    image: "/assets/images/Ring/WomenRing/Ring3.webp",
    category: "Rings",
    gender: "Women",
    occasion: "Casual Wear",
    karatage: 18,
  },
  {
    id: 12,
    name: "Curvy Classy Gold and Diamond Ring",
    productDetails:
      "Classy, curvy and built to last, this glossy finished diamond ring will go great with your everyday wear. The perfect gift for the everyday woman.",
    price: 15000.0,
    quantity: 1,
    image: "/assets/images/Ring/WomenRing/Ring4.webp",
    category: "Rings",
    gender: "Women",
    occasion: "Casual Wear",
    karatage: 18,
  },
  {
    id: 13,
    name: "Classy Hexagonal Ring",
    productDetails:
      "Sleek and striking, this geometric ring with carvings is designed to illuminate your everyday style. The perfect accessory for fashionable lady.",
    price: 18000.0,
    quantity: 1,
    image: "/assets/images/Ring/WomenRing/Ring5.webp",
    category: "Rings",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 22,
  },
  {
    id: 14,
    name: "Subtle Stacked Ring",
    productDetails:
      "A unique ring for a unique personality! Look sophisticated in every outfit on every occasion when you adorn this stacked ring!",
    price: 20000.0,
    quantity: 1,
    image: "/assets/images/Ring/WomenRing/Ring6.webp",
    category: "Rings",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 22,
  },
  {
    id: 15,
    name: "Knotting Stackable Ring",
    productDetails:
      "This set has a central ring with a charming knot pattern, stacked above three minimal rings. This glamorous design is impossible to ignore!",
    price: 22000.0,
    quantity: 1,
    image: "/assets/images/Ring/WomenRing/Ring7.webp",
    category: "Rings",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 22,
  },
  {
    id: 16,
    name: "Shimmering Two-head Diamond Ring",
    productDetails:
      "The perfect choice for your next party ensemble, this two-head ring has been crafted masterfully to complement all your moods.",
    price: 25000.0,
    quantity: 1,
    image: "/assets/images/Ring/WomenRing/Ring8.webp",
    category: "Rings",
    gender: "Women",
    occasion: "Casual Wear",
    karatage: 18,
  },
  {
    id: 17,
    name: "Surreal Artistic Ring",
    productDetails:
      "Add a touch of grace to your new beginning with this surreal ring. Crafted beautifully, this design is artistic and charming and calls for attention.",
    price: 30000.0,
    quantity: 1,
    image: "/assets/images/Ring/WomenRing/Ring9.webp",
    category: "Rings",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 22,
  },
  {
    id: 18,
    name: "Quiet Promises Finger Ring",
    productDetails:
      "Make a promise to yourself to always stay on top of your fashion game and flaunt your charming style with this finger ring that completes your look. The only piece of jewellery you'll need to make your mark, this ring is designed for every day.",
    price: 35000.0,
    quantity: 1,
    image: "/assets/images/Ring/WomenRing/Ring10.webp",
    category: "Rings",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 18,
    materialColor: "Rose",
  },
  {
    name: "Interwoven Gold Drop Earrings",
    productDetails:
      "With these hypnotic danglers, making an unforgettable style statement is effortlessly easy. Make this brilliant pair a staple in your Collection for special occasions!",
    gender: "Women",
    id: 19,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings1.webp",
    price: 60000,
    occasion: "Modern Wear",
    materialColor: "yellow",
  },
  {
    name: " Dainty Diamond Drop Earrings",
    productDetails:
      "Timelessly elegant, this pair of earrings add to your charming appeal. An ideal choice for everyday wear, these danglers are effortlessly casual.",
    gender: "Women",
    id: 20,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings2.webp",
    price: 80000,
    occasion: "Modern Wear",
    materialColor: "yellow",
  },
  {
    name: "Floral Mesh Drop Earrings",
    productDetails:
      "Feel special everyday with the dazzling touch of these diamond drop earrings designed to be fuss-free, keeping in mind the needs of the modern woman.",
    gender: "Women",
    productType: "Drops",
    occasion: "Modern Wear",
    id: 21,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings3.webp",
    price: 120000,
    materialColor: "yellow",
  },
  {
    name: "Lovely Chic Diamond Drop Earrings",
    productDetails:
      "Make a subtle and dainty statement with your elaborate outfits with the help of these drop earrings featuring diamonds and gold arcs.",
    gender: "Women",
    productType: "Drops",
    occasion: "Casual Wear",
    id: 22,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings4.webp",
    price: 70000,
    materialColor: "yellow",
  },
  {
    name: "Subtle Radiance Diamond Stud Earrings",
    productDetails:
      "Illuminate your style with the dainty allure of these minimal diamond stud earrings, meticulously crafted to add a hint of sparkle to any outfit.",
    gender: "Women",
    productType: "Studs",
    occasion: "Casual Wear",
    id: 23,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings5.webp",
    price: 65000,
    materialColor: "yellow",
  },
  {
    name: "Glamorous Chandbali Earrings",
    productDetails:
      "Dip your style in the enchanting beauty of these drop earrings. Intricate in design and mesmerising in its appeal, it's the perfect accessory for elegant and understated ensembles.",
    gender: "Women",
    productType: "Drops",
    occasion: "Traditional And Ethnic Wear",
    id: 24,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings6.webp",
    price: 55000,
    materialColor: "yellow",
  },
  {
    name: "Radiant Diamond Stud Earrings",
    productDetails:
      "Elevate your style sensibilities with these diamond-studded stud earrings, seamlessly blending contemporary flair with timeless elegance.",
    gender: "Women",
    productType: "Studs",
    occasion: "Modern Wear",
    id: 25,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings7.webp",
    price: 90000,
    materialColor: "yellow",
  },

  {
    name: "Geometric Allure Hoop Earrings",
    productDetails:
      "A hexagonal diamond studded pattern dangles daintily from a circular hoop in an alluringly delicate yet eye-catching design. These hoop earrings inspire confidence during board meetings or elevate your look during casual outings day after day.",
    gender: "Women",
    productType: "Hoops",
    occasion: "Office Wear",
    karatage: "18",
    id: 26,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings8.webp",
    price: 95000,
    materialColor: "yellow",
  },
  {
    name: "Surreal Jali Work Gold Drop Earrings",
    productDetails:
      "Surreal and spectacular, these drop earrings are a true winner, when it comes to elevating your occasion wear The elaborate design will work effortlessly for special occasions",
    gender: "Women",
    id: 27,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings9.webp",
    price: 120000,
    materialColor: "yellow",
  },
  {
    name: "Essential  Diamond Stud Earrings",
    productDetails:
      "Unveil the charm of these diamond stud earrings, meticulously designed to complement her style sensibilities with their timeless elegance and sophisticated allure.",
    gender: "Women",
    productType: "Studs",
    occasion: "Casual Wear",
    id: 28,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings10.webp",
    price: 47500,
    materialColor: "yellow",
  },
  {
    name: "Netted Miracles Hoop Earrings",
    productDetails:
      "An eye catching fishnet design makes these captivating hoop earrings the piece de resistance of your jewellery Collection. A unique design that goes perfectly with any outfit of your choice, you can enjoy these earrings daily, without any hesitation.",
    gender: "Women",
    productType: "Hoops",
    occasion: "Office Wear",
    karatage: "22",
    id: 29,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings11.webp",
    price: 65000,
    materialColor: "yellow",
  },
  {
    name: "Dainty Dance Hoop Earrings",
    productDetails:
      "If you thought simple is basic, think again! This simple diamond hoop earring set is anything but basic. Don it with every possible outfit from denims to trousers to shorts or dresses. This dainty yet eye catchy design is perfect for everyday wear.",
    gender: "Women",
    productType: "Hoops",
    occasion: "Office Wear",
    karatage: "18",
    id: 30,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings12.webp",
    price: 46600,
    materialColor: "yellow",
  },
  {
    name: "Contemporary Blend Hoop Earrings",
    productDetails:
      "A traditionally simple blend of classic simplicity meets modern style in this hoop earring set with danglers. Its unassuming design is perfect for everyday wear and can be teamed up with any outfit to instantly add a dash of style to your look.",
    gender: "Women",
    productType: "Hoops",
    occasion: "Traditional And Ethnic Wear",
    karatage: "22",
    id: 31,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings13.webp",
    price: 75000,
    materialColor: "yellow",
  },
  {
    name: "Eternal Sparkle Diamond Stud Earrings",
    productDetails:
      "Unveil the allure of understated luxury with these diamond stud earrings that exude timeless charm and brilliance, making them the perfect accessory for both casual and formal occasions.",
    gender: "Women",
    productType: "Studs",
    occasion: "Casual Wear",
    id: 32,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings14.webp",
    price: 85600,
    materialColor: "yellow",
  },
  {
    name: "Alluring Gold Chandelier Drop Earrings",
    productDetails:
      "Inspired by the evergreen elegance of leaves, these drop earrings are all about unmatched allure Be the spotlight at every occasion with this pair",
    gender: "Women",
    id: 33,
    quantity: 1,
    category: "earrings",
    image: "/assets/images/Earrings/Earrings15.webp",
    price: 40000,
    materialColor: "yellow",
    occasion: "Formal",
  },
  {
    name: "Elegant Flower Diamond Pendant",
    productDetails:
      "This pendant is the perfect fit for elegant and glamorous women. The chain in this image is for representative purpose only and the product comes without a chain.",
    pendantHeight: "1.7 Cm",
    pendantWidth: "1.1 Cm",
    gender: "Women",
    id: 34,
    category: "pendants",
    image: "/assets/images/Pendents/Pendent1.webp",
    price: 42000,
    quantity: 1,
    materialColor: "yellow",
    occasion: "Formal",
  },
  {
    name: "Minimalistic Dazzle Diamond Pendant",
    productDetails:
      "A fusion of minimalistic timelessness and clean lines, this diamond pendant emanates a dainty allure that exquisitely captures the essence of femininity. Please Note: The chain in the image is for representative purpose only and the product comes without a chain.",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: "18",
    id: 35,
    category: "pendants",
    image: "/assets/images/Pendents/Pendent2.webp",
    price: 50000,
    materialColor: "yellow",
    quantity: 1,
  },
  {
    name: "Radiant  Diamond Snowflake Pendant",
    productDetails:
      "Crafted with meticulous precision, the 'Radiant Frost' pendant captures the unique geometry of a snowflake. As you wear the pendant, you become a part of the timeless magic of winter. Please note: The chain in the image is for representative purpose only, and the actual product comes without a chain.",
    pendantHeight: "2.6 Cm",
    pendantWidth: "1.6 Cm",
    gender: "Women",
    id: 36,
    category: "pendants",
    image: "/assets/images/Pendents/Pendent3.webp",
    price: 45000,
    occasion: "Formal",
    materialColor: "yellow",
    quantity: 1,
  },
  {
    name: "Gilded Heartbeat Diamond  Pendant",
    productDetails:
      "This pendant encapsulates the essence of love and elegance in a graceful drop. With this pendant, you wear not just a piece of jewellery, but a tribute to the enduring emotions that shape our lives. Please note: The chain in the image is for representative purpose only, and the actual product comes without a chain.",
    pendantHeight: "1.8 Cm",
    pendantWidth: "1 Cm",
    gender: "Women",
    id: 37,
    category: "pendants",
    image: "/assets/images/Pendents/Pendent4.webp",
    price: 20000,
    occasion: "Formal",
    materialColor: "yellow",
    quantity: 1,
  },
  {
    name: "Simply Elegant Diamond Pendant",
    productDetails:
      "Nestled within the heart of the leaf, a mesmerizing arrangement of diamonds evokes the sparkling dewdrops that adorn leaves in the early morning sunlight. Please note: The chain in the image is for representative purpose only, and the actual product comes without a chain.",
    pendantHeight: "2 Cm",
    pendantWidth: "1 Cm",
    gender: "Women",
    id: 38,
    category: "pendants",
    image: "/assets/images/Pendents/Pendent5.webp",
    price: 20000,
    occasion: "Formal",
    materialColor: "yellow",
    quantity: 1,
  },
  {
    name: "Geometric Pattern Rose Gold Pendant",
    productDetails:
      "Versatile and timeless, this oval-shaped pendant complements both casual and traditional attire. The intricate design adds a touch of elegance, making it a perfect accessory for any occasion.The chain in the image is for representative purpose only and the actual product comes without a chain.",
    gender: "Women",
    productType: "OTHERS",
    occasion: "Traditional And Ethnic Wear",
    id: 39,
    category: "pendants",
    image: "/assets/images/Pendents/Pendent6.webp",
    price: 35000,
    materialColor: "yellow",
    quantity: 1,
  },
  {
    name: "Dazzling Dahlia Ruby Pendant",
    productDetails:
      "The pendant's design is inspired by the captivating beauty of a dahlia in full bloom. Crafted in radiant 22 Karat yellow gold, this pendant showcases a mesmerizing array of round ruby stones, forming each delicate petal and gracing the center of the flower. The chain in the image is for representative purpose only, and the actual product comes without a chain.",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: "22",
    id: 40,
    category: "pendants",
    image: "/assets/images/Pendents/Pendent7.webp",
    price: 15000,
    materialColor: "yellow",
    quantity: 1,
  },
  {
    name: "Gilded Spiral Diamond Snail Pendant",
    productDetails:
      "The 'Gilded Spiral' pendant pays homage to the intricate pattern of a snail's shell. The rose gold serves as a canvas, allowing diamonds to elegantly trace the curves and contours. Please note: The chain in the image is for representative purpose only, and the actual product comes without a chain.",
    pendantHeight: "2.2 Cm",
    pendantWidth: "1.3 Cm",
    gender: "Women",
    id: 41,
    category: "pendants",
    image: "/assets/images/Pendents/Pendent8.webp",
    price: 20500,
    occasion: "Formal",
    materialColor: "yellow",
    quantity: 1,
  },
  {
    name: "Cute Floral Diamond Pendant",
    productDetails:
      "Pair these cute floral pendant with your casual attires and bloom everyday. The chain in the image is for representative purpose only and the actual product comes without a chain.",
    pendantHeight: "1.74 Cm",
    pendantWidth: "1.16 Cm",
    gender: "Women",
    id: 42,
    category: "pendants",
    image: "/assets/images/Pendents/Pendent9.webp",
    price: 10000,
    occasion: "Formal",
    materialColor: "yellow",
    quantity: 1,
  },
  {
    name: "Charming Yellow Gold Leaf Pendant",
    productDetails:
      "Rejoice in the glory of eternal love with this darling twin leaf pendant. Two stippled leaves are inlaid in a matte gold heart frame, in a classically romantic design.",
    pendantHeight: "1.91 Cm",
    pendantWidth: "1.2 Cm",
    gender: "Women",
    id: 43,
    category: "pendants",
    image: "/assets/images/Pendents/Pendent10.webp",
    price: 8000,
    occasion: "Formal",
    materialColor: "yellow",
    quantity: 1,
  },
  {
    id: 44,
    name: "Beautiful Linked Bracelet",
    productDetails:
      "The abstract design of this bracelet makes it the perfect choice for those with an easygoing sense of style. Perfect to radiate that subtle shine all day.",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 22,
    quantity: 1,
    image: "/assets/images/Bracelet/bracelet1.png",
    price: 13500,
    materialColor: "yellow",
    category: "bracelet",
  },
  {
    id: 45,
    name: "Radiant Links Bracelet",
    productDetails:
      "Make heads turn with this pretty, interconnected loop-style bracelet. This piece looks simple and adorable and is designed to go well with all your styles.",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 22,
    quantity: 1,
    image: "/assets/images/Bracelet/bracelet2.png",
    price: 12000,
    materialColor: "yellow",
    category: "bracelet",
  },
  {
    id: 46,
    name: "Brilliant Geometric Bracelet",
    productDetails:
      "This petite bracelet is designed to illuminate your everyday style without being over the top. Simple and elegant, this piece is sure to be your style staple!",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 22,
    quantity: 1,
    image: "/assets/images/Bracelet/bracelet3.png",
    price: 9200,
    materialColor: "yellow",
    category: "bracelet",
  },
  {
    id: 47,
    name: "Whimsical Wings Butterfly Bracelet",
    productDetails:
      "This is a captivating piece that embodies the grace and beauty of nature's most cherished creatures. Crafted with meticulous artistry, this exquisite bracelet features a stunning butterfly motif at its center, rendered in lustrous gold and dazzling diamonds.",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 18,
    quantity: 1,
    image: "/assets/images/Bracelet/bracelet4.png",
    price: 35000,
    materialColor: "yellow",
    category: "bracelet",
  },
  {
    id: 48,
    name: "Radiant Flowers Diamond Bracelet",
    productDetails:
      "This classy bracelet is simple yet elegant. The dual toned gold and diamond flowers are guaranteed to highlight your natural beauty.",
    gender: "Women",
    occasion: "Casual Wear",
    karatage: 18,
    quantity: 1,
    image: "/assets/images/Bracelet/bracelet5.png",
    price: 10000,
    materialColor: "yellow",

    category: "bracelet",
  },
  {
    id: 49,
    name: "Heartstring Diamond Bracelet",
    productDetails:
      "Communicate your love language with our uncomplicated designs from the latest Dots & Dashes Collection!",
    gender: "Women",
    occasion: "Casual Wear",
    karatage: 18,
    quantity: 1,
    image: "/assets/images/Bracelet/bracelet6.png",
    price: 23000,
    materialColor: "yellow",
    category: "bracelet",
  },
  {
    id: 50,
    name: "Life is Roses Diamond Bracelet",
    productDetails:
      "A reminder of budding love and youthful mirth, celebrate your beautiful journey of love with our 'Pretty in Pink' Collection",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 18,
    quantity: 1,
    image: "/assets/images/Bracelet/bracelet7.png",
    price: 22500,
    materialColor: "yellow",
    category: "bracelet",
  },
  {
    id: 51,
    name: "Leadership Leo Bracelet",
    productDetails:
      "Vivacious, dramatic and loves to be the centre of attention. This charismatic sign has the fiery spirit of a lion. Celebrate your inner lion with this charming bracelet.",
    gender: "Unisex",
    occasion: "Casual Wear",
    karatage: 18,
    quantity: 1,
    image: "/assets/images/Bracelet/bracelet8.png",
    price: 40000,
    materialColor: "yellow",
    category: "bracelet",
  },
  {
    id: 52,
    name: "Regal Charm Bracelet For Men",
    productDetails:
      "Unveil a symbol of opulence and refined style with this men's gold bracelet, a statement piece that mirrors the discerning taste of today's modern gentleman.",
    gender: "Men",
    occasion: "Modern Wear",
    karatage: 22,
    quantity: 1,
    image: "/assets/images/Bracelet/bracelet9.png",
    price: 30000,
    materialColor: "yellow",
    category: "bracelet",
  },
  {
    id: 53,
    name: "Celestial Diamond Crescent Bracelet",
    productDetails:
      "Wearing the Celestial Diamond Crescent Bracelet is like wearing a piece of the night sky close to your wrist. It's to celebrate the cycles of change, to honour the mysteries that the night sky holds, and to embody the wonder that defines your spirit.",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 18,
    quantity: 1,
    image: "/assets/images/Bracelet/bracelet10.png",
    price: 20000,
    materialColor: "yellow",
    category: "bracelet",
  },
  {
    id: 54,
    name: "Brilliant Lariat Necklace",
    productDetails:
      "The grandeur of gold and the contemporary lariat style makes this high polish necklace a must have addition to your closet!",
    Collection: "Glamdays",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 22,
    price: 60938,
    quantity: 1,
    category: "necklace",
    materialColor: "yellow",
    image: "/assets/images/Necklace/necklace1.png",
  },
  {
    id: 55,
    name: "Whispers of Love Diamond Necklace",
    productDetails:
      "Immerse yourself in the tender elegance of this diamond necklace, where every gleaming facet reflects the depth of your most cherished emotions.",
    Collection: "Bestsellers",
    gender: "Women",
    occasion: "Casual Wear",
    karatage: 18,
    price: 92045,
    quantity: 1,
    category: "necklace",
    materialColor: "yellow",
    image: "/assets/images/Necklace/necklace2.png",
  },
  {
    id: 56,
    name: "Sparkling Hearts Diamond Necklace",
    productDetails:
      "A radiant expression of the enchanting mysteries of love, this diamond charms necklace whispers the secrets of the profound connection between two delicate hearts.",
    Collection: "Valentines",
    gender: "Women",
    "Product Type": "STUDDED",
    occasion: "Casual Wear",
    price: 129996,
    quantity: 1,
    category: "necklace",
    materialColor: "yellow",
    image: "/assets/images/Necklace/necklace3.png",
  },
  {
    id: 57,
    name: "An Aura of Traditional  Necklace",
    productDetails:
      "Immerse yourself in the luminous glow of this gold necklace as it gracefully drapes around your neck, casting a warm and resplendent aura. Symbolizing luxury, it exudes a sense of timeless elegance.",
    Collection: "Bestsellers",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 22,
    price: 301688,
    quantity: 1,
    category: "necklace",
    materialColor: "yellow",
    image: "/assets/images/Necklace/necklace4.png",
  },
  {
    id: 58,
    name: "A Golden Nest Diamond Necklace",
    productDetails:
      'Let the flow of your life be as graceful as the glide of our beautiful designs in the "Go with the Flow" Collection!',
    Collection: "Bestsellers",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 18,
    price: 67614,
    quantity: 1,
    category: "necklace",
    materialColor: "yellow",
    image: "/assets/images/Necklace/necklace5.png",
  },
  {
    id: 59,
    name: "Twisty Linked Necklace",
    productDetails:
      "Add a twist of elegance to your style. Captivating design and golden allure make it the perfect statement piece for those who appreciate elegance and style.",
    Collection: "String It",
    gender: "Women",
    "Product Type": "PLAINGOLD",
    occasion: "Casual Wear",
    price: 54251,
    quantity: 1,
    category: "necklace",
    materialColor: "yellow",
    image: "/assets/images/Necklace/necklace6.png",
  },
  {
    id: 60,
    name: " Shri Ganesh Rudraksh Necklace",
    productDetails:
      "This Ganesha necklace will make for an auspicious gift for your loved one. The simple, abstract design makes it a great choice for everyday wear.",
    Collection: "Padmaja",
    gender: "Unisex",
    occasion: "Modern Wear",
    price: 82097,
    quantity: 1,
    category: "necklace",
    materialColor: "yellow",
    image: "/assets/images/Necklace/necklace7.png",
  },
  {
    id: 61,
    name: "Unmatched  Diamond Necklace",
    productDetails:
      "Grace yourself with this diamond necklace, a dazzling embodiment of sophistication that goes beyond fleeting trends and let the radiance of diamonds elevate your presence to a level of unmatched opulence.",
    Collection: "Bestsellers",
    gender: "Women",
    occasion: "Casual Wear",
    karatage: 18,
    price: 208955,
    quantity: 1,
    category: "necklace",
    materialColor: "yellow",
    image: "/assets/images/Necklace/necklace8.png",
  },
  {
    id: 62,
    name: "In the Flow Diamond Necklace",
    productDetails:
      'Let the flow of your life be as graceful as the glide of our beautiful designs in the "Go with the Flow" Collection!',
    Collection: "Bestsellers",
    gender: "Women",
    occasion: "Modern Wear",
    karatage: 18,
    price: 93272,
    quantity: 1,
    category: "necklace",
    materialColor: "yellow",
    image: "/assets/images/Necklace/necklace9.png",
  },
  {
    id: 63,
    name: "Riona Pearl Stud Earrings",
    productDetails:
      "Dainty yet elegant, these stud earrings are timeless in every possible way Treat yourself to these beauties today!",
    quantity: 1,
    category: "Pearl",
    Collection: "Swarnam",
    gender: "Women",
    price: "22054",
    materialColor: "Gold",
    image: "/assets/images/Pearl/Pearl1.png",
    occasion: "Formal",
  },
  {
    id: 64,
    name: "Classy Elegant Pearl Pendant",
    productDetails:
      "Whether your attire is western or traditional, this Gold and Pearl pendant flawlessly complements any outfit. You don't need an occasion when you have the perfect accessory! The chain in the image is for representative purpose only and the product comes without a chain.",
    quantity: 1,
    category: "Pearl",
    Collection: "Bestsellers",
    gender: "Women",
    price: "9428",
    materialColor: "Gold",
    image: "/assets/images/Pearl/Pearl2.png",
    occasion: "Formal",
  },
  {
    id: 65,
    name: "Sophisticated Pearl Drop Earrings",
    productDetails:
      "These classic drop earrings are enticing and elegant. The shimmering cubic zirconias and pristine pearls are guaranteed to highlight your natural beauty.",
    quantity: 1,
    category: "Pearl",
    Collection: "Padmaja",
    gender: "Women",
    price: "30994",
    materialColor: "Gold",
    image: "/assets/images/Pearl/Pearl3.png",
    occasion: "Formal",
  },
  {
    id: 66,
    name: "Minimalist  Yellow Gold And Pearl Studs",
    productDetails:
      "The lone luminous pearl in these stud earrings can enchant a room full of people. Embrace the elegance of this pair by making it a part of your daily style.",
    quantity: 1,
    category: "Pearl",
    Collection: "Bestsellers",
    gender: "Women",
    price: "11463",
    materialColor: "Gold",
    image: "/assets/images/Pearl/Pearl4.png",
    occasion: "Formal",
  },
  {
    id: 67,
    name: "Graceful Pearl and Diamond Pendant",
    productDetails:
      "Add a touch of elegance to your style with this pendant. The chain in this image is for representative purpose only and the product comes without a chain.",
    quantity: 1,
    category: "Pearl",
    Collection: "Padmaja",
    gender: "Women",
    price: "34116",
    materialColor: "Gold",
    image: "/assets/images/Pearl/Pearl5.png",
    occasion: "Formal",
  },
  {
    id: 68,
    name: "Dazzling Pearl and Diamond Earrings",
    productDetails:
      "Radiate with an unmatched glamour or keep it understated at elegant affairs with these lovely earrings, featuring shimmery diamonds and pearls",
    quantity: 1,
    category: "Pearl",
    Collection: "Padmaja",
    gender: "Women",
    price: "40609",
    materialColor: "Gold",
    image: "/assets/images/Pearl/Pearl6.png",
    occasion: "Formal",
  },
  {
    id: 69,
    name: "Pearls & Petals Gold Stud Earrings",
    productDetails:
      "The centerpiece of each earring features a bright and lustrous pearl, exuding a captivating sheen that reflects the light like shimmering moonbeams on a tranquil night. Surrounding each pearl is a delicate arrangement of gold petals, meticulously crafted to mimic the beauty of nature's blossoms.",
    quantity: 1,
    category: "Pearl",
    Collection: "Bestsellers",
    gender: "Women",
    price: "36811",
    materialColor: "Gold",
    image: "/assets/images/Pearl/Pearl7.png",
    occasion: "Formal",
  },
  {
    id: 70,
    name: "Cascading Pearl and Diamond Necklace",
    productDetails:
      "Elevate the opulence of grand gatherings with this pearls and diamonds necklace. The cascading elegant design is sure to leave the crowd hypnotised.",
    quantity: 1,
    category: "Pearl",
    Collection: "Bestsellers",
    gender: "Women",
    price: "69726",
    materialColor: "Gold",
    image: "/assets/images/Pearl/Pearl8.png",
    occasion: "Formal",
  },
  {
    id: 71,
    name: "Ethereal Diamond and Pearl Earrings",
    productDetails:
      "Embrace your graceful side with these blooming, diamond encrusted drop earrings, with a dollop of pearl hanging from a slender gold chain!",
    quantity: 1,
    category: "Pearl",
    Collection: "Bestsellers",
    gender: "Women",
    price: "79276",
    materialColor: "Gold",
    image: "/assets/images/Pearl/Pearl9.png",
    occasion: "Formal",
  },
  {
    id: 72,
    name: "Tejaswi Necklace Set",
    productDetails:
      "This inverted lotus pendant with enamel detailing is truly a work of art 7ith the bloom rendered to life like beauty with enamel details. Seamless gradation between various hues and tints of pink add a touch of delicacy and unparalleled beauty to this floral piece!",
    quantity: 1,
    category: "Pearl",
    Collection: "Alekhya",
    gender: "Women",
    price: "347199",
    materialColor: "Gold",
    image: "/assets/images/Pearl/Pearl10.png",
    occasion: "Formal",
  },
];
export default product;
